src/firesale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('item.urls')),
    path('admin/', admin.site.urls),
    path("notifications/", include("notifications.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('profile/', include('person.urls')),
    path('item/', include('item.urls')),
    path('checkout/', include('transaction.urls')),
    path(
        'privacy-policy',
        TemplateView.as_view(
            template_name="privacy_policy.html"
        ),
        name='privacy-policy'
    ),
]

handler404 = 'firesale.views.page_not_found'

src/item/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="item-index"),
    path('<int:id>', views.get_item_by_id, name='item-details'),
    path('create-item', views.create_item, name='create-item'),
    path('delete-item/<int:id>', views.delete_item, name='delete-item'),
    path('update-item/<int:id>', views.update_item, name='update-item'),
    path('see-offers/<int:id>', views.see_offers, name='see-offers'),
    path('my-items', views.my_items, name='my-items'),
    path('my-offers', views.my_offers, name='my-offers'),
]

src/item/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


def item_photo_directory_path(instance, filename):
    return f'item/{instance.item.name}/{filename}'


def validate_offer_status(value):
    if value not in ['Accepted', 'Pending', 'Declined', 'Confirmed']:
        raise ValidationError(
            "Status must be Accepted, Pending, Declined or Confirmed")
    return value


def validate_item_status(value):
    if value not in ['Available', 'Waiting for payment', 'Sold']:
        raise ValidationError(
            "Status must be Available, Waiting for payment or Sold")
    return value


class Seller(models.Model):
    rating = models.PositiveIntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


class SellerRating(models.Model):
    rating = models.PositiveIntegerField(default=0)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.seller)


class Item(models.Model):
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=255,
                              validators=[validate_item_status],
                              default='Available')
    condition = models.CharField(max_length=255)
    description = models.TextField()
    category = models.CharField(max_length=255)
    price = models.IntegerField()
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


class ItemImage(models.Model):
    image = models.ImageField(upload_to=item_photo_directory_path)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.item.name}-image-{self.id}'


class Offer(models.Model):
    status = models.CharField(max_length=255,
                              validators=[validate_offer_status],
                              default='Pending')
    amount = models.IntegerField()
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.status}-{self.amount}'

src/notifications/models.py
from django.db import models
from django.contrib.auth.models import User


class Inbox(models.Model):
    # NOTE: incs/decs on unread implemented in service and interface classes
    unread = models.PositiveIntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}-inbox'


class Notification(models.Model):
    title = models.CharField(max_length=50)
    message = models.CharField(max_length=256)
    date = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)
    inbox = models.ForeignKey(Inbox, on_delete=models.CASCADE)
    # NOTE: specifies the name of a url pattern as seen in urls.py
    next_path = models.CharField(
        max_length=50, blank=True, default="notification-list")

    def __str__(self):
        return f'{self.title}-{self.date}'

src/transaction/forms/checkout_form.py
from django.forms import CharField, Form, IntegerField

from dj_cleavejs import *


class PaymentForm(Form):
    creditcard = IntegerField(widget=CreditCard())
    date = CharField(widget=CleaveWidget(blocks=[2, 2], delimiter="/"))
    cvc = CharField(widget=CleaveWidget(blocks=[3]))

src/templates/checkout/contact_information.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'checkout/css/main.css' %}" />
  <h2 class="checkout-title">Contact information</h2>
  <form class="checkout-info-wrapper" action="/checkout/payment-information">
    <div class="checkout-info-list">
      <label for="full_name">
        Full name:
        <input type="text" id="full_name" name="full_name" required />
      </label>
      <label for="street_name">
        Street name:
        <input type="text" id="street_name" name="street_name" required />
      </label>
      <label for="house_number">
        House number:
        <input type="text" id="house_number" name="house_number" required />
      </label>
    </div>
    <div class="checkout-info-list">
      <label for="city">
        City:
        <input type="text" id="city" name="city" required />
      </label>
      <label for="country">
        Country:
        <select id="country" name="country" required>
          <option value="" disabled selected></option>
          {% for country in countries %}<option value="{{ country }}">{{ country }}</option>{% endfor %}
        </select>
      </label>
      <label for="postal_code">
        Postal code:
        <input type="text" id="postal_code" name="postal_code" required />
      </label>
    </div>
    <input type="submit"
           value="Continue"
           class="btn main-button checkout-continue-button" />
  </form>
{% endblock %}

src/templates/checkout/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'checkout/css/main.css' %}"></link>
<div class="checkout-wrapper">
  <h1 class="text-center">Basket</h1>
  <hr>
  {% if basket %}
    {% for checkout_item in basket %}
      <div class="single-checkout-item-wrapper">
        <img src="{{ checkout_item.item.itemimage_set.first.image.url }}"
             alt="item image"
             width="100"
             height="100" />
        <div class="checkout-item-details">
          <b>{{ checkout_item.item.name }}</b>
          <span>Your offer: {{ checkout_item.amount }} kr</span>
        </div>
      </div>
      <hr>
    {% endfor %}
    <a class="btn main-button checkout-items-button"
       href="/checkout/contact-information">Checkout</a>
  {% else %}
    <p class="checkout-error-text">There are no items in your basket.</p>
  {% endif %}
</div>
{% endblock %}

src/templates/checkout/payment_information.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'checkout/css/main.css' %}" />
  <a href="/checkout/contact-information" class="checkout-go-back">
    <i class="fa-solid fa-chevron-left"></i>
    <span>Go back</span>
  </a>
  <h2 class="checkout-title">Payment information</h2>
  <form class="checkout-info-wrapper" action="/checkout/review">
    <div class="checkout-info-list">
      <label for="card_holder">Name of cardholder:</label>
      <input type="text" id="card_holder" name="card_holder" required>
      <label for="card_number">Card number:</label>
      {{ form.creditcard }}
      <!-- <input type="text" id="card_number" name="card_number" required> -->
    </div>
    <div class="checkout-info-list">
      <label for="expiration_date">Expiration date:</label>
      {{ form.date }}
      <!-- <input type="text" id="expiration_date" name="expiration_date" required> -->
      <label for="cvc">CVC:</label>
      {{ form.cvc }}
      <!-- <input type="text" id="cvc" name="cvc" required> -->
    </div>
    <input type="submit"
           value="Continue"
           class="btn main-button checkout-continue-button" />
  </form>
  {{ form.media }}
{% endblock %}

src/templates/checkout/review.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'checkout/css/main.css' %}" />
  <a href="/checkout/payment-information" class="checkout-go-back">
    <i class="fa-solid fa-chevron-left"></i>
    <span>Go back</span>
  </a>
  <div class="review-wrapper">
    <div class="review-info">
      <h2 class="checkout-title">Contact information</h2>
      <label for="full_name">
        Full name:
        <input type="text" id="full_name" name="full_name" disabled />
      </label>
      <label for="street_name">
        Street name:
        <input type="text" id="street_name" name="street_name" disabled />
      </label>
      <label for="house_number">
        House number:
        <input type="text" id="house_number" name="house_number" disabled />
      </label>
      <label for="city">
        City:
        <input type="text" id="city" name="city" disabled />
      </label>
      <label for="country">
        Country:
        <input type="text" id="country" name="country" disabled />
      </label>
      <label for="postal_code">
        Postal code:
        <input type="text" id="postal_code" name="postal_code" disabled />
      </label>
      <h2 class="checkout-title">Payment information</h2>
      <label for="card_holder">
        Name of cardholder:
        <input type="text" id="card_holder" name="card_holder" disabled />
      </label>
      <label for="card_number">
        Card number:
        <input type="text" id="id_creditcard" name="id_creditcard" disabled />
      </label>
      <label for="expiration_date">
        Expiration date:
        <input type="text" id="id_date" name="id_date" disabled />
      </label>
      <label for="cvc">
        CVC:
        <input type="text" id="id_cvc" name="id_cvc" disabled />
      </label>
    </div>
    <div class="review-purchase">
      <h2 class="checkout-title">Order summary</h2>
      {% for checkout_item in basket %}
        <div class="single-checkout-item-wrapper"
             id="selling-item-{{ checkout_item.id }}">
          <img src="{{ checkout_item.item.itemimage_set.first.image.url }}"
               id="selling-image-{{ checkout_item.id }}"
               alt="item image"
               width="100"
               height="100" />
          <div class="checkout-item-details">
            <b id="selling-name-{{ checkout_item.id }}">{{ checkout_item.item.name }}</b>
            <span id="selling-amount-{{ checkout_item.id }}">Your offer: {{ checkout_item.amount }} kr</span>
          </div>
        </div>
        <hr>
      {% endfor %}
      <h3 class="checkout-title">Subtotal: {{ total }} kr</h3>
    </div>
    <a class="btn main-button confirm-purchase-btn"
       href="/checkout/thank-you"
       id="confirm_purchase">Confirm purchase</a>
  </div>
{% endblock %}

src/templates/checkout/thank_you.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'checkout/css/main.css' %}" />
  <!-- Confetti script borrowed from https://codepen.io/bananascript/pen/EyZeWm -->
  <script src="{% static 'checkout/js/confetti.js' %}"></script>
  <div class="checkout-wrapper">
    <h1 class="text-center">Thank you for your purchase!</h1>
    <hr>
    <div class="thank-you-sold-items"></div>
    <a class="btn main-button checkout-items-button" href="/">Return to home page</a>
  </div>
{% endblock %}